name: Playwright Tests

on: [push, pull_request]

env:
  my_user: standard_user
  my_password: secret_sauce
  my_performance_glitched_user: performance_glitch_user

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        run: allure generate allure-assets -c --single-file

      - name: Upload Allure report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: allure-report
          path: allure-report/