name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 18 * * *' # Runs daily at 6 PM UTC  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        
    - name: Install dependencies
      run: npm install

    - name: Install Java
      uses: actions/setup-java@v4.7.1
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev  

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Create test credentials file
      run: |
        echo "my_user=standard_user" > .creds.env
        echo "my_password=secret_sauce" >> .creds.env
        echo "my_performance_glitched_user=performance_glitch_user" >> .creds.env
        echo "my_invalid_username=invalid_user" >> .creds.env
        echo "my_invalid_password=invalid_password" >> .creds.env
        
    - name: Run Playwright tests
      run: npx playwright test --reporter=html

    - name: Generate Allure report
      if: always()
      run: allure generate allure-results -o allure-report --clean  

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Playwright Report Allure
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30

    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30    

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
      
